baseURL = "https://capricorn.github.io/"
languageCode = "en-us"
title = "~cap"
theme = "cactus"

[params]
    colortheme = "white"

[[params.social]]
  name = "github"
  link = "https://github.com/capricorn"

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/capdevel"
